const books = {
  "fantasy-1": {
    id: "fantasy-1",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: "Rp. 200.000",
    rating: 4.5,
    category: "fantasy",
    description:
      "The first book in the Harry Potter series, now in a special edition paperback with colorful stenciled edges! A must-have for fans and a stunning gift for collectors of all age",
    publishDate: "May 7th 1998",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "223",
    isbn: "978-0-7475-3269-9",
    dimensions: "19.8 x 12.9 x 2.3 cm",
    weight: "290 grams",
    coverType: "Paperback",
    genre: "Fantasy, Adventure, Children's Fiction",
    readingAge: "8 years and up",
    series: "Book 1 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-sorcerer-photoshoot.png",
      front: "../assets/images/harrypotter-sorcerer-frontview.jpg",
      back: "../assets/images/harrypotter-sorcerer-backview.jpeg",
    },
    overview: [
      "Harry Potter has never played a sport while flying on a broomstick. He's never worn a cloak of invisibility, befriended a giant, or helped hatch a dragon. All Harry knows is a miserable life with the Dursleys, his horrible aunt and uncle, and their abominable son, Dudley. Harry's room is a tiny closet at the foot of the stairs, and he hasn't had a birthday party in eleven years.",
      "But then a mysterious letter arrives by owl messenger: a letter with an invitation to an incredible place called Hogwarts School of Witchcraft and Wizardry. And there he finds not only friends, aerial sports, and magic around every corner, but a great destiny that's been waiting for him… if Harry can survive the encounter.",
    ],
  },

  "fantasy-2": {
    id: "fantasy-2",
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling",
    price: "Rp. 210.000",
    rating: 4.5,
    category: "fantasy",
    description:
      "The second year at Hogwarts brings a mysterious threat to the school.",
    publishDate: "July 2nd 1998",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "251",
    isbn: "978-0-7475-3849-3",
    dimensions: "19.8 x 12.9 x 2.5 cm",
    weight: "310 grams",
    coverType: "Paperback",
    genre: "Fantasy, Mystery, Adventure",
    readingAge: "8 years and up",
    series: "Book 2 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-chamber-photoshoot.png",
      front: "../assets/images/harrypotter-chamber-frontview.jpg",
      back: "../assets/images/harrypotter-chamber-backview.png",
    },
    overview: [
      "Ever since Harry had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to Hogwarts School of Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature who says that if Harry returns to Hogwarts, disaster will strike... And strike it does.",
      "For in Harry's second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls' bathroom. But then the real trouble begins: Someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects... Harry Potter himself!",
    ],
  },
  "fantasy-3": {
    id: "fantasy-3",
    title: "Harry Potter and the Prisoner of Azkaban",
    author: "J.K. Rowling",
    price: "Rp. 220.000",
    rating: 3.5,
    category: "fantasy",
    description: "A dangerous prisoner has escaped and is looking for Harry.",
    publishDate: "July 8th 1999",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "317",
    isbn: "978-0-7475-4215-5",
    dimensions: "19.8 x 12.9 x 2.8 cm",
    weight: "340 grams",
    coverType: "Paperback",
    genre: "Fantasy, Thriller, Adventure",
    readingAge: "9 years and up",
    series: "Book 3 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-prisoner-photoshoot.png",
      front: "../assets/images/harrypotter-prisoner-frontview.png",
      back: "../assets/images/harrypotter-prisoner-backview.png",
    },
    overview: [
      "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort. Now he has escaped, leaving only two clues as to where he might be headed",
      "Harry Potter's defeat of You-Know-Who was Black's downfall as well. And the Azkaban guards heard Black muttering in his sleep, Harry Potter isn't safe, not even within the walls of his magical school, surrounded by his friends. Because on top of it all, there may well be a traitor in their midst.",
    ],
  },
  "fantasy-4": {
    id: "fantasy-4",
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    price: "Rp. 230.000",
    rating: 5,
    category: "fantasy",
    description: "A magical tournament puts Harry in unexpected danger.",
    publishDate: "July 8th 2000",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "636",
    isbn: "978-0-7475-4624-5",
    dimensions: "19.8 x 13.1 x 4.2 cm",
    weight: "550 grams",
    coverType: "Paperback",
    genre: "Fantasy, Action, Mystery",
    readingAge: "10 years and up",
    series: "Book 4 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-goblet-photoshoot.png",
      front: "../assets/images/harrypotter-goblet-frontview.png",
      back: "../assets/images/harrypotter-goblet-backview.jpg",
    },
    overview: [
      "Harry Potter wants to get away from the pernicious Dursleys and go to the Quidditch World Cup with Hermione, Ron, and the Weasleys. He wants to dream about Cho Chang, his crush (and maybe do more than dream). He wants to find out about the mysterious event involving two other rival schools of magic",
      "a competition that hasn't happened for hundreds of years. He wants to be a normal, fourteen-year-old wizard. Unfortunately for Harry Potter, he's not normal; he’s different — even by wizarding standards. And in this case, different can be deadly.",
    ],
  },
  "fantasy-5": {
    id: "fantasy-5",
    title: "Harry Potter and the Order of the Phoenix",
    author: "J.K. Rowling",
    price: "Rp. 240.000",
    rating: 4.5,
    category: "fantasy",
    description:
      "Dark times ahead as the wizarding world refuses to believe Voldemort is back.",
    publishDate: "June 21st 2003",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "766",
    isbn: "978-0-7475-5100-3",
    dimensions: "19.8 x 13.2 x 5 cm",
    weight: "600 grams",
    coverType: "Paperback",
    genre: "Fantasy, Drama, Adventure",
    readingAge: "11 years and up",
    series: "Book 5 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-phoenix-photoshoot.png",
      front: "../assets/images/harrypotter-phoenix-frontview.png",
      back: "../assets/images/harrypotter-phoenix-backview.png",
    },
    overview: [
      "There is a door at the end of a silent corridor. And it's haunting Harry Potter's dreams. Why else would he be waking in the middle of the night, screaming in terror? It's not just the upcoming O.W.L. exams; a new teacher with a personality like poisoned honey; a disgruntled house-elf; or even the growing threat of He-Who-Must-Not-Be-Named.",
      "Now Harry Potter is faced with the unreliability of the very government of the magical world and the impotence of the authorities at Hogwarts. Despite this (or perhaps because of it), he finds depth and strength in his friends beyond what even he knew, boundless loyalty, and unbearable sacrifice.",
    ],
  },
  "fantasy-6": {
    id: "fantasy-6",
    title: "Harry Potter and the Half-Blood Prince",
    author: "J.K. Rowling",
    price: "Rp. 250.000",
    rating: 4.5,
    category: "fantasy",
    description: "Secrets about Voldemort’s past come to light.",
    publishDate: "July 16th 2005",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "607",
    isbn: "978-0-7475-8108-6",
    dimensions: "19.8 x 13.2 x 4.1 cm",
    weight: "530 grams",
    coverType: "Paperback",
    genre: "Fantasy, Romance, Adventure",
    readingAge: "11 years and up",
    series: "Book 6 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-prince-photoshoot.png",
      front: "../assets/images/harrypotter-prince-frontview.png",
      back: "../assets/images/harrypotter-prince-backview.png",
    },
    overview: [
      "The war against Voldemort is not going well; even Muggle governments are noticing. Hermione scans the pages of the Daily Prophet, reading out terrible news. Dumbledore is absent from Hogwarts for long stretches of time, and the Order of the Phoenix has already suffered losses. And yet... As in all wars, life goes on.",
      "Sixth-year students learn to Apparate — and lose a few eyebrows in the process. Teenagers flirt and fight and fall in love. Classes are tough, though Harry receives some extraordinary help from the mysterious Half-Blood Prince. And all the while Harry searches for the full and complex story of the boy who became Lord Voldemort, hoping to find what may be his only vulnerability.",
    ],
  },
  "fantasy-7": {
    id: "fantasy-7",
    title: "Harry Potter and the Deathly Hallows",
    author: "J.K. Rowling",
    price: "Rp. 270.000",
    rating: 3.5,
    category: "fantasy",
    description: "The final battle between good and evil begins.",
    publishDate: "July 21st 2007",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "759",
    isbn: "978-0-545-01022-1",
    dimensions: "19.8 x 13.3 x 4.8 cm",
    weight: "590 grams",
    coverType: "Paperback",
    genre: "Fantasy, War, Adventure",
    readingAge: "12 years and up",
    series: "Book 7 of 7 in the Harry Potter series",
    images: {
      photoshoot: "../assets/images/harrypotter-hallow-photoshoot.png",
      front: "../assets/images/harrypotter-hallow-frontview.png",
      back: "../assets/images/harrypotter-hallow-backview.png",
    },
    overview: [
      "The Deathly Hallows are three legendary, powerful magical artifacts: the Elder Wand, the Resurrection Stone, and the Cloak of Invisibility. According to legend, the owner of all three becomes the Master of Death.",
      "They were said to have been created by Death and given to three brothers in the Peverell family. The story of the Deathly Hallows was originally a tale in Beedle the Bard's book, but many wizards considered it just a myth. ",
    ],
  },
  "fantasy-8": {
    id: "fantasy-8",
    title: "Dune",
    author: "Frank Herbert",
    price: "Rp. 280.000",
    rating: 3.5,
    category: "fantasy",
    description:
      "A masterpiece of the Science Fiction genre, Dune laid the foundation for many of the epics that followed. Frank Herbert addresses overarching themes of family politics, religion, environment and the all-encompassing temptation of power,",
    publishDate: "June 23rd 1965",
    publisher: "Bloomsbury Publishing",
    language: "English",
    pages: "412",
    isbn: "978-0-565-01052-1",
    dimensions: "19.8 x 13.3 x 4.8 cm",
    weight: "590 grams",
    coverType: "Paperback",
    genre: "Science Fiction, Adventure, Philosophical",
    readingAge: "15 years and up",
    series: "Book 1 of 5 in the Dune series",
    images: {
      photoshoot: "../assets/images/dune-first-photoshoot.svg",
      front: "../assets/images/dune-first-frontview.jpg",
      back: "../assets/images/dune-first-backview.png",
    },
    overview: [
      "After facing masses of rejection letters, Frank Herbert finally published Dune in 1965. More than thirty years later, his magnificent Dune chronicles have sold more copies than any other science fiction novels in history. This first book is set on the desert planet Arrakis, a world drawn as vividly and terrifyingly as any in literature.",
      "Dune begins the story of the man known as Maud'dib, a hero who will guide his great family in their ambition to bring about humankind's most ancient and unattainable dream to found the perfect society. Perhaps only J.R.R. Tolkien's Lord of the Rings has as loyal a following as Frank Herbert's masterpiece. But no work of science fiction has had as profound an imaginative influence.",
    ],
  },
  "fantasy-9": {
    id: "fantasy-9",
    title: "Dune Messiah",
    author: "Frank Herbert",
    price: "Rp. 285.000",
    rating: 5,
    category: "fantasy",
    description:
      "The epic continues with Dune Messiah, chronicling the aftermath of Paul Atreides’ rise to emperor and the dark legacy of the jihad.",
    publishDate: "October 15th 1969",
    publisher: "Chilton Books",
    language: "English",
    pages: "256",
    isbn: "978-0-441-17271-9",
    dimensions: "19.8 x 13.3 x 3.2 cm",
    weight: "450 grams",
    coverType: "Paperback",
    genre: "Science Fiction, Politics, Philosophy",
    readingAge: "15 years and up",
    series: "Book 2 of 5 in the Dune series",
    images: {
      photoshoot: "../assets/images/dune-messiah-photoshoot.svg",
      front: "../assets/images/dune-messiah-frontview.jpg",
      back: "../assets/images/dune-messiah-backview.png",
    },
    overview: [
      "The best-selling science-fiction series of all time continues! This second installment explores new developments on the desert planet Arrakis, with its intricate social order and its strange threatening environment. Dune Messiah picks up the story of the man known as Maud'dib",
      " heir to a power unimaginable, bringing to fruition an ambition of unparalleled scale: the centuries-old scheme to create a superbeing who reigns not in the heavens but among men. But the question is: Do all paths of glory lead to the grave?",
    ],
  },
  "fantasy-10": {
    id: "fantasy-10",
    title: "Children of Dune",
    author: "Frank Herbert",
    price: "Rp. 290.000",
    rating: 4,
    category: "fantasy",
    description:
      "The children of Paul Atreides must navigate a web of prophecy, politics, and rebellion in this powerful third book of the Dune saga.",
    publishDate: "April 21st 1976",
    publisher: "G.P. Putnam's Sons",
    language: "English",
    pages: "416",
    isbn: "978-0-441-29363-6",
    dimensions: "20.3 x 13.5 x 3.5 cm",
    weight: "470 grams",
    coverType: "Paperback",
    genre: "Science Fiction, Family, Power",
    readingAge: "15 years and up",
    series: "Book 3 of 5 in the Dune series",
    images: {
      photoshoot: "../assets/images/dune-children-photoshoot.svg",
      front: "../assets/images/dune-children-frontview.jpg",
      back: "../assets/images/dune-chidren-backview.png",
    },
    overview: [
      "The Children of Dune are twin siblings Leto and Ghanima Atreides, whose father, the Emperor Paul Muad’Dib,'disappeared'in the desert wastelands of Arrakis nine years ago. Like their father, the twins possess supernormal abilities—making them valuable to their manipulative aunt Alia, who rules the Empire in the name of House Atreides.",
      "Facing treason and rebellion on two fronts, Alia’s rule is not absolute. The displaced House Corrino is plotting to regain the throne while the fanatical Fremen are being provoked into open revolt by the enigmatic figure known only as The Preacher. Alia believes that by obtaining the secrets of the twins’ prophetic visions, she can maintain control over her dynasty.",
    ],
  },
  "fantasy-11": {
    id: "fantasy-11",
    title: "God Emperor of Dune",
    author: "Frank Herbert",
    price: "Rp. 300.000",
    rating: 3,
    category: "fantasy",
    description:
      "Set thousands of years after the original trilogy, the God Emperor reigns supreme, seeking to fulfill a prophetic Golden Path for humanity.",
    publishDate: "May 28th 1981",
    publisher: "G.P. Putnam's Sons",
    language: "English",
    pages: "496",
    isbn: "978-0-441-29464-0",
    dimensions: "21.0 x 14.0 x 4.0 cm",
    weight: "510 grams",
    coverType: "Paperback",
    genre: "Science Fiction, Philosophical, Political",
    readingAge: "16 years and up",
    series: "Book 4 of 5 in the Dune series",
    images: {
      photoshoot: "../assets/images/dune-god-photoshoot.svg",
      front: "../assets/images/dune-god-frontview.jpg",
      back: "../assets/images/dune-god-backview.jpg",
    },
    overview: [
      "Millennia have passed on Arrakis, and the once-desert planet is green with life. Leto Atreides, the son of the world’s savior, the Emperor Paul Muad’Dib, is still alive but far from human. To preserve humanity’s future, he sacrificed his own by merging with a sandworm, granting him near immortality as God Emperor of Dune for the past thirty-five hundred years.",
      "Leto’s rule is not a benevolent one. His transformation has made not only his appearance but his morality inhuman. A rebellion, led by Siona, a member of the Atreides family, has risen to oppose the despot’s rule. But Siona is unaware that Leto’s vision of a Golden Path for humanity requires her to fulfill a destiny she never wanted—or could possibly conceive....",
    ],
  },
  "kids-1":{
    id: "kids-1",
    title: "The Wild Robot",
    author: "Peter Brown",
    price: "Rp. 180.000",
    rating: 4.5,
    category: "kids",
    description: "A robot awakens on a remote island and must learn to survive in the wild.",
    publishDate: "April 5th 2016",
    publisher: "Little, Brown Books for Young Readers",
    language: "English",
    pages: "288",
    isbn: "978-0316381994",
    dimensions: "20.0 x 13.5 x 2.8 cm",
    weight: "400 grams",
    coverType: "Paperback",
    genre: "Adventure, Sci-Fi",
    readingAge: "8 - 12 years",
    series: "The Wild Robot #1",
    images: {
        "photoshoot": "../assets/images/robot-wild-photoshoot.svg",
        "front": "../assets/images/robot-wild-frontview.jpg",
        "back": "../assets/images/robot-wild-backview.jpg"
    },
    overview: [
        "Roz the robot finds herself stranded on a remote, untamed island after a shipwreck. She must learn to survive in a world where she doesn't belong, facing weather, wild animals, and unfamiliar instincts.",
        "As Roz adapts to her surroundings, she forms unexpected bonds with the island's creatures and begins to discover her own sense of purpose.Her journey is one of self-discovery, acceptance, and the power of kindness. Roz transforms from an outsider into a vital part of the wild."
    ]
  },
  "kids-2": {
    id: "kids-2",
    title: "The Wild Robot Protects",
    author: "Peter Brown",
    price: "Rp. 180.000",
    rating: 3.5,
    category: "kids",
    description: "Roz the robot must protect her island home and animal friends from new dangers in this heartwarming adventure.",
    publishDate: "March 21st 2023",
    publisher: "Little, Brown Books for Young Readers",
    language: "English",
    pages: "288",
    isbn: "978-0-316-46447-5",
    dimensions: "20.3 x 13.5 x 2.2 cm",
    weight: "320 grams",
    coverType: "Hardcover",
    genre: "Children's Fiction, Adventure, Robots",
    readingAge: "8 - 12 years",
    series: "Book 3 of The Wild Robot series",
    images: {
      photoshoot: "../assets/images/robot-protect-photoshoot.svg",
      front: "../assets/images/robot-protect-frontview.jpg",
      back: "../assets/images/robot-protect-backview.jpg"
    },
    overview: [
      "After settling into life on the island, Roz is faced with new dangers threatening her animal family. When mysterious intruders arrive and begin harming the wildlife, Roz steps up to defend those she loves.She must navigate difficult decisions, protect the young, and stand against injustice.",
      "As tension rises, Roz’s courage, compassion, and cleverness shine through, proving that even a robot can become a true protector.This story explores loyalty, bravery, and the strength found in unity."
    ]
  },
  "kids-3": {
    id: "kids-3",
    title: "The Wild Robot Escapes",
    author: "Peter Brown",
    price: "Rp. 175.000",
    rating: 3,
    category: "kids",
    description: "Roz escapes from the farm and embarks on a journey to find her way home.",
    publishDate: "March 13th 2018",
    publisher: "Little, Brown Books for Young Readers",
    language: "English",
    pages: "288",
    isbn: "978-0-316-38199-4",
    dimensions: "20.3 x 13.5 x 2.2 cm",
    weight: "320 grams",
    coverType: "Hardcover",
    genre: "Children's Fiction, Adventure, Robots",
    readingAge: "8 - 12 years",
    series: "Book 2 of The Wild Robot series",
    images: {
      photoshoot: "../assets/images/robot-escape-photoshoot.svg",
      front: "../assets/images/robot-escape-frontview.jpg",
      back: "../assets/images/robot-escape-backview.jpg"
    },
    overview: [
      "Roz is taken from her home and forced to work on a human farm, separated from her animal friends. But she never stops dreaming of returning to her island. While she works with new humans and animals, Roz searches for a way to escape.",
      "Her journey back is filled with danger, allies, and lessons about freedom and belonging. She discovers that home is not just a place—it's where you are loved and accepted."
    ]
  },
  "kids-4": {
    id: "kids-4",
    title: "The Bad Guys #1",
    author: "Aaron Blabey",
    price: "Rp. 160.000",
    rating: 5,
    category: "kids",
    description: "Meet the Bad Guys: Mr. Wolf, Mr. Shark, Mr. Snake, and Mr. Piranha. They want to be heroes, but their plans don’t always go as expected!",
    publishDate: "December 27th 2016",
    publisher: "Scholastic",
    language: "English",
    pages: "144",
    isbn: "978-0-545-91240-2",
    dimensions: "19.0 x 13.0 x 1.0 cm",
    weight: "200 grams",
    coverType: "Paperback",
    genre: "Children's Fiction, Humor, Adventure",
    readingAge: "7 - 10 years",
    series: "Book 1 of The Bad Guys series",
    images: {
      photoshoot: "../assets/images/badguy-1-photoshoot.svg",
      front: "../assets/images/badguy-1-frontview.jpeg",
      back: "../assets/images/badguy-1-backview.jpeg"
    },
    overview: [
      "Mr. Wolf, Mr. Snake, Mr. Shark, and Mr. Piranha are always seen as the bad guys. But they want to change their image and become heroes instead. So, they form a team and plan their first good deed: rescuing dogs from the pound.",
      "Of course, things don't go smoothly, leading to hilarious chaos and unexpected teamwork. This story is packed with humor, action, and friendship, proving anyone can be a good guy if they try."
    ]
  },
  "kids-5": {
    id: "kids-5",
    title: "How To Train Your Dragon",
    author: "Cressida Cowell",
    price: "Rp. 170.000",
    rating: 4,
    category: "kids",
    description: "Hiccup Horrendous Haddock III must capture a dragon as part of his Viking initiation, but nothing goes as planned!",
    publishDate: "February 1st 2003",
    publisher: "Little, Brown Books for Young Readers",
    language: "English",
    pages: "240",
    isbn: "978-0-316-80087-6",
    dimensions: "19.8 x 12.9 x 1.8 cm",
    weight: "250 grams",
    coverType: "Paperback",
    genre: "Children's Fiction, Fantasy, Adventure",
    readingAge: "8 - 12 years",
    series: "Book 1 of How To Train Your Dragon series",
    images: {
      photoshoot: "../assets/images/httyd-1-photoshoot.svg",
      front: "../assets/images/httyd-1-frontview.jpeg",
      back: "../assets/images/httyd-1-backview.jpg"
    },
    overview: [
      "Hiccup is a young Viking who lives in a village where dragons are feared and hunted. But everything changes when he captures and befriends a dragon he names Toothless. Together, they challenge ancient traditions and uncover the truth about dragons.",
      "Hiccup must prove that understanding and compassion are stronger than fear. This is a tale of unlikely friendship, bravery, and finding your own path."
    ]
  },
  "kids-6": {
    id: "kids-6",
    title: "The Lorax",
    author: "Dr. Seuss",
    price: "Rp. 150.000",
    rating: 4.5,
    category: "kids",
    description: "The classic tale of the Lorax, who speaks for the trees and fights to protect the environment.",
    publishDate: "August 12th 1971",
    publisher: "Random House",
    language: "English",
    pages: "72",
    isbn: "978-0-394-82337-9",
    dimensions: "28.0 x 20.0 x 0.5 cm",
    weight: "180 grams",
    coverType: "Hardcover",
    genre: "Children's Fiction, Environment, Classic",
    readingAge: "5 - 9 years",
    series: "Standalone",
    images: {
      photoshoot: "../assets/images/lorax-1-photoshoot.svg",
      front: "../assets/images/lorax-1-frontview.jpeg",
      back: "../assets/images/lorax-1-backview.jpg"
    },
    overview: [
      "A young boy seeks the truth about what happened to the trees in his town, leading him to hear the tale of the Lorax. The Lorax is a creature who spoke for the trees, warning against greed and destruction. Through a colorful and powerful story, the boy learns about caring for nature and making better choices.",
      "The Lorax's message is simple: unless someone cares a whole lot, nothing is going to get better. This book is a call to protect the planet and cherish what we have before it's gone."
    ]
  },
  "kids-7": {
    id: "kids-7",
    title: "Paddington Goes to Town",
    author: "Michael Bond",
    price: "Rp. 165.000",
    rating: 5,
    category: "kids",
    description: "Paddington Bear’s adventures continue as he explores the town and gets into all sorts of mischief.",
    publishDate: "September 1st 1968",
    publisher: "HarperCollins",
    language: "English",
    pages: "160",
    isbn: "978-0-00-675343-2",
    dimensions: "19.7 x 12.9 x 1.2 cm",
    weight: "210 grams",
    coverType: "Paperback",
    genre: "Children's Fiction, Humor, Adventure",
    readingAge: "7 - 10 years",
    series: "Book 8 of Paddington Bear series",
    images: {
      photoshoot: "../assets/images/paddington-1-photoshoot.svg",
      front: "../assets/images/paddington-1-frontview.jpg",
      back: "../assets/images/paddington-1-backview.jpg"
    },
    overview: [
      "Paddington Bear is back with another set of heartwarming adventures in the charming town he now calls home. Though he always means well, Paddington often finds himself in the middle of unexpected trouble, from joining a town festival to helping out in the local theater. With his trademark hat, marmalade sandwiches, and kind heart, Paddington brings joy to everyone he meets—even if they don’t always see it at first.",
       "Despite the chaos he causes, his innocence and honesty always shine through, turning even the worst mishaps into happy endings. This delightful tale celebrates curiosity, community, and how a little kindness can make a big difference in everyday life. Paddington teaches both children and adults how to be gentle, thoughtful, and hopeful, no matter what challenges arise."
    ]
  },
  "kids-8": {
    id: "kids-8",
    title: "The Big Friendly Giant",
    author: "Roald Dahl",
    price: "Rp. 155.000",
    rating: 3.5,
    category: "kids",
    description: "Sophie befriends the Big Friendly Giant and together they set out to stop the man-eating giants.",
    publishDate: "October 1st 1982",
    publisher: "Puffin Books",
    language: "English",
    pages: "224",
    isbn: "978-0-14-241038-7",
    dimensions: "19.8 x 12.9 x 1.6 cm",
    weight: "220 grams",
    coverType: "Paperback",
    genre: "Children's Fiction, Fantasy, Adventure",
    readingAge: "8 - 12 years",
    series: "Standalone",
    images: {
      photoshoot: "../assets/images/bfg-1-photoshoot.svg",
      front: "../assets/images/bfg-1-frontview.jpg",
      back: "../assets/images/bfg-1-backview.jpg"
    },
    overview: [
      "Sophie is snatched from her orphanage by a giant—but not just any giant. He's the BFG, the Big Friendly Giant, who collects dreams and refuses to eat children. Together, they hatch a plan to stop the evil giants who do harm.",
      "Their friendship grows as they take their daring plan all the way to the Queen of England. This story is a magical blend of courage, imagination, and the power of standing up for what's right."
    ]
  },
  "kids-9": {
    id: "kids-9",
    title: "Elemental",
    author: "Disney Pixar",
    price: "Rp. 170.000",
    rating: 5,
    category: "kids",
    description: "A story of friendship and discovery in a city where fire, water, land, and air residents live together.",
    publishDate: "June 16th 2023",
    publisher: "Disney Press",
    language: "English",
    pages: "128",
    isbn: "978-1-368-08623-2",
    dimensions: "23.0 x 15.0 x 1.0 cm",
    weight: "210 grams",
    coverType: "Hardcover",
    genre: "Children's Fiction, Fantasy, Movie Tie-In",
    readingAge: "6 - 10 years",
    series: "Standalone",
    images: {
      photoshoot: "../assets/images/elemental-1-photoshoot.svg",
      front: "../assets/images/elemental-1-frontview.jpg",
      back: "../assets/images/elemental-1-backview.jpg"
    },
    overview: [
      "In Element City, where fire, water, earth, and air residents live side by side—but rarely mix—Ember, a fiery and passionate girl, meets Wade, a calm and emotional water boy. Their unlikely friendship turns into something deeper as they challenge the social norms that keep elements apart. Together, they journey through the city and face their fears, discovering that they have more in common than they thought.",
      "Ember struggles with balancing her family’s expectations and her own desires, while Wade shows her the value of expressing emotions and letting go. Elemental is a stunning and emotional story about identity, family legacy, and breaking down barriers. It proves that love and understanding can transcend even the most fundamental differences—even fire and water can find harmony."
    ]
  },
  "kids-10": {
    id: "kids-10",
    title: "Turning Red",
    author: "Disney Pixar",
    price: "Rp. 160.000",
    rating: 3.5,
    category: "kids",
    description: "Mei Lee discovers she turns into a giant red panda whenever she gets too excited!",
    publishDate: "March 1st 2022",
    publisher: "Disney Press",
    language: "English",
    pages: "144",
    isbn: "978-1-368-07723-0",
    dimensions: "23.0 x 15.0 x 1.0 cm",
    weight: "210 grams",
    coverType: "Hardcover",
    genre: "Children's Fiction, Fantasy, Movie Tie-In",
    readingAge: "7 - 11 years",
    series: "Standalone",
    images: {
      photoshoot: "../assets/images/turningred-1-photoshoot.svg",
      front: "../assets/images/turningred-1-frontview.jpg",
      back: "../assets/images/turningred-1-backview.jpg"
    },
    overview: [
      "Mei Lee is a 13-year-old girl torn between being her mother's obedient daughter and the chaos of adolescence. Things get even more complicated when she starts turning into a giant red panda whenever she gets emotional. As Mei navigates school, friends, and her changing identity, she learns to embrace her true self.",
      "The film is a joyful, heartfelt look at puberty, family expectations, and growing up. It celebrates the power of accepting yourself—flaws, panda and all."
    ]
  },
  "kids-11": {
    id: "kids-11",
    title: "Coco",
    author: "Disney Pixar",
    price: "Rp. 165.000",
    rating: 4.5,
    category: "kids",
    description: "Miguel embarks on a journey to the Land of the Dead to discover his family’s history and love for music.",
    publishDate: "October 10th 2017",
    publisher: "Disney Press",
    language: "English",
    pages: "144",
    isbn: "978-1-368-01323-8",
    dimensions: "23.0 x 15.0 x 1.0 cm",
    weight: "210 grams",
    coverType: "Hardcover",
    genre: "Children's Fiction, Fantasy, Movie Tie-In",
    readingAge: "7 - 11 years",
    series: "Standalone",
    images: {
      photoshoot: "../assets/images/coco-1-photoshoot.svg",
      front: "../assets/images/coco-1-frontview.jpg",
      back: "../assets/images/coco-1-backview.jpg"
    },
    overview: [
      "Miguel has always dreamed of becoming a famous musician like his idol Ernesto de la Cruz, but his family has banned music for generations. On Día de los Muertos, Miguel’s determination leads him to steal a guitar that mysteriously transports him to the Land of the Dead. There, he meets his ancestors and a funny trickster named Héctor, who helps him uncover a hidden family history.",
      "As Miguel searches for the truth, he learns that remembering those who came before us is more important than fame or fortune. With rich visuals, heartfelt songs, and deep cultural roots, Coco is a moving celebration of love, memory, and family. It reminds us that honoring our loved ones keeps them alive in spirit, and that following your heart can lead you back home."
    ]
  },
};


